Fixed a bug with start Null Error
RTUITLab/Excursion360-Builder pull request #9
Opened 2020-11-14 08:28 UTC by leonis13579

Исправлена ошибка с статичной инициализацией переменных из префабов. Сделанн геттер, который проверяет на null и, при необходимости, заново инициализирует переменную.

2020-11-14 17:33 UTC, CAPCHIK requested changes
Необходимо использовать свойства C#, вместо методов getSome()

2020-11-14 17:33 UTC, CAPCHIK commented on Editor/TourEditor.cs
> +    public static GameObject getStatePrefab()
В C# есть специальный инструмент - свойства (Property), и именно ими необходимо реализовывать функционал геттеров

2020-11-14 17:33 UTC, CAPCHIK commented on Editor/TourEditor.cs
> +    public static GameObject getViewSpherePrefab()
Аналогично с методом выше

2020-11-21 06:35 UTC, leonis13579 commented
C# type coding

2020-11-23 18:30 UTC, closed without merging